image: alpine:3.8

stages:
  - docs
  - publish

generate-docs:
  stage: docs
  script:
    - apk add --update python3
    - pip3 install python-gitlab
    - python3 generate_pages.py
  artifacts:
    paths:
    - public/

pages:
  stage: publish
  variables:
    ACME_DIR: public/.well-known/acme-challenge
  dependencies:
    - generate-docs
  artifacts:
    paths:
      - public/
  script:
    - mkdir -p ${ACME_DIR}
    - echo ${ACME_CHALLENGE} > ${ACME_DIR}/$(echo ${ACME_CHALLENGE} | cut -c1-43)
  only:
    - master
